### ISSUE TITLE
Docker setup failed 

### ISSUE THREAD

**Issue by parkbj26** [sea-bass/turtlebot3_behavior_demos#24]
I was just following down this, https://github.com/sea-bass/turtlebot3_behavior_demos 

1. git clone https://github.com/sea-bass/turtlebot3_behavior_demos.git

2. cd turtlebot3_behavior_demos

3. docker compose build

However, at 3, I found the problem that the build failed with the below comments.

The detailed error can be found in the attached image files.

--------------------------------------------------------------------------------------------------------

ERROR [overlay 5/6] RUN source /turtlebot3_ws/install/setup.bash  && colcon build --symlink-install

....

/overlay_ws/src/tb3_autonomy/src/autonomy_node.cpp:12:10: fatal error: behaviortree_cpp/loggers/bt_zmq_publisher.h: No such file or directory

FYI:

![20230412_164414](https://user-images.githubusercontent.com/26245971/231398554-44906c66-b952-4af0-b1ba-ef93274606c1.png)

**Comment by sea-bass** [comment]
It seems like BehaviorTree.CPP removed their old ZMQ published in https://github.com/BehaviorTree/BehaviorTree.CPP/commit/4c789eae68eba30124e98a4ff09db796e5582d11 recently, so that breaks the `master` branch of that library.

For now, I've reverted the BehaviorTree.CPP repo to the `4.1.1` branch, but the next step is to upgrade the repo to move from Groot to Groot 2. Made https://github.com/sea-bass/turtlebot3_behavior_demos/issues/26 to track this.

Can you pull the latest version of this repo and try again?
